### ISSUE TITLE
Multiple metal ingots and blocks

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#13]
It's annoying how there are 4 different types of copper and other metals.

Can we fix this?

**Comment by CRezent** [comment]
This is fixable but takes a lot of work to do right. There is also a high probability of messing something up because we need to edit block ID's and all the recipies that use those block ids so we can still craft all the recipies. This includes the ore blocks, ingot blocks, blocks of metal, and any other form there may be of that specific type of metal for all the multiple variants. 

I think that it will be much better and easier to just deal with this in game as fixing it will likely mess something up we will not discover for a long time in server.

**Comment by Weikardzaena** [comment]
Actually after playing around with Chisel, I realized you can chisel blocks of, say, copper from one mod to the next.  So you can do conversions between mods with only one type of ore in the world.  The downside is that you're required to have a block of the stuff since you can't do it on ingots.  Also I'm not sure what will happen to recipes if you delete the duplicate ores from the world but not the metal ingots/blocks.  It might just be way simpler to leave everything in.

**Comment by CRezent** [comment]
Do you know where the files containing block ids are located? I cannot find them in several of the mods that generate blocks and I cannot find the vanilla ones.

**Comment by superzanti** [comment]
Turns out we might be able to fix this issue as we go with ModTweaker2 and Minetweaker3

**Comment by CRezent** [comment]
I can also disable world gen for duplicates of the ores. I can also adjust ore density / spawnrate to make sure there is still the same ammount that spawns. I am not sure if there would be less. I cannot think of a good way to compare that. This is a simple fix in the config files. If you use a smelter or any of the IC2 machines to smelt the ores, you get the ic2 version of the ingots so the crafting seems to be the same because that is how I smelted all my ingots anyways.

**Comment by CRezent** [comment]
This should be closed with the new fix I gave to Nik. We can use the fix or not but the fix is in.
