### ISSUE TITLE
Chisel mod creating blocks

### ISSUE THREAD

**Issue by Weikardzaena** [superzanti/TheVerse#20]
The Chisel mod allows users to change blocks from one form to another that might be used in crafting recipes.  For instance, you can chisel Stone into Mossy Stone, and then mine the mossy stone to get balls of moss.  While the vast majority of the Chiseled blocks are purely aesthetics, some of them might be used to bypass certain crafting recipes.  We should find those that are not aesthetic and try to disable them.

EDIT:

And yes, this works in survival mode.

**Comment by Weikardzaena** [comment]
Alright, I might have missed one or two, but these were the blocks I found that can change into blocks that you could not craft with the materials you used in the original recipe:

Cobblestone <---> Whitestone/Blackstone
Glass <---> Soul Glass, Heat Glass, Quite Clear Glass, Runic Glass
Steel <---> Refined Iron
Stone <---> Mossy stone bricks, cracked stone bricks, chiseled stone bricks

**Comment by superzanti** [comment]
Any suggested fixes?

**Comment by Weikardzaena** [comment]
The only fix I can think of without access to source would be to disable chisel functionality for these blocks entirely.  Which would be a shame to not be able to chisel cobblestone and glass and such.  An alternative that I haven't looked into is the ModTweaker.  Perhaps there's a way to disable certain chisel options there.

**Comment by superzanti** [comment]
After analyzing it seems that much of the block changes you can make with chisel don't break the game. Especially since chisels break and take time.

If we find anything game breaking later we can simply disable that block in chisel.

For now I've just removed turning stone into mossy stone. A ball of moss is required for this.

Closed. [commit](https://github.com/superzanti/TheVerse/commit/cd4dc7800e541790917a7a142acee1baaabf425b)
